### ISSUE TITLE
[FEAT] 특정 챗봇에 대해 특정 유저의 좋아요 여부 반환

### ISSUE THREAD

**Issue by 13155a1** [ssodam-project/BackEnd#15]
## 🛠 Issue

특정 챗봇에 대해서, 접속한 유저가 좋아요를 눌렀는지 안 눌렀는지 반환
<br/>

## 📝 To-do

- [x] 좋아요 여부 반환 기능 구현
- [x] 테스트
- [x] 배포 후 테스트 (IP 주소로 유저가 잘 식별이 되는지 확인)
- [x] api 문서 작성
